[build]
builder = "NIXPACKS"
buildCommand = "npm ci --legacy-peer-deps --include=dev && npm run build"

[deploy]
startCommand = "npm run serve"
healthcheckPath = "/api/products"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
